name: Build and Package Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: imgease  # 指定 pyproject.toml 所在目录
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install PyInstaller
        working-directory: imgease  # 指定 pyproject.toml 所在目录
        run: |
          poetry run pip install pyinstaller

      #将 convert.py 和 grayscale.py 分别打包为独立的 .exe 文件。你可以调整打包的脚本路径，打包成一个或多个可执行文件。
      - name: Build Executable with PyInstaller
        working-directory: imgease  # 指定 pyproject.toml 所在目录
        run: |
          poetry run pyinstaller --onefile src/imgease/convert.py  # 打包 convert 脚本
          poetry run pyinstaller --onefile src/imgease/grayscale.py  # 打包 grayscale 脚本
          #
      # 检查是否生成了.exe文件
      - name: Verify exe files
        working-directory: imgease  # 指定 pyproject.toml 所在目录
        run: |
          if not exist dist\imgease-convert.exe exit 1
          if not exist dist\imgease-grayscale.exe exit 1

      #使用 PowerShell 的 Compress-Archive 命令将生成的可执行文件压缩为一个 zip 文件，方便上传和分发。
      - name: Create a zip of executables
        working-directory: imgease  # 指定 pyproject.toml 所在目录
        run: |
          Compress-Archive -Path dist/* -DestinationPath imgease_windows_executables.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: imgease_windows_executables.zip
