name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.0'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  #3.x

    - name: Install dependencies
      working-directory: imgease  # 指定 pyproject.toml 所在目录
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-dev

    - name: Build package
      working-directory: imgease  # 指定 pyproject.toml 所在目录
      run: |
        poetry build

    - name: Publish to PyPI
      working-directory: imgease  # 指定 pyproject.toml 所在目录
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish --username __token__ --password $PYPI_TOKEN
